security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
       main:
          entity: 
             class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            
            # em login path utilizar o name da rota não o login ela está em @Route ... name..
            # no default_target_path: dashboard significa que após se logar a primeira página a aparecer
            # será a rota dashboard, em always_use_default_target_path significa que sempre utilizará o dashboard como entrada no login
            
            form_login: 
               login_path: login
               check_path: login
               default_target_path: dashboard
               always_use_default_target_path: true
            # https://symfony.com/doc/current/security/form_login_setup.html
            
            logout:
               path: /logout
               target: /admin/login

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    # Minha nota: Somente o ROLE_ADMIN acessa a route 'relatorios' 
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/relatorios, roles: ROLE_ADMIN }
        - { path: ^/admin/dashboard, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }
        
    # estamos dizendo que o ROLE_ADMIN também é o ROLE_USER
    role_hierarchy:
       ROLE_ADMIN: ROLE_USER
       
       
        
    encoders:
       App\Entity\User: 
          algorithm: bcrypt
          cost: 12