<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX8g3Kmx\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX8g3Kmx/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerX8g3Kmx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerX8g3Kmx\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \ContainerX8g3Kmx\srcApp_KernelProdDebugContainer(array(
    'container.build_hash' => 'X8g3Kmx',
    'container.build_id' => '73dd7cd5',
    'container.build_time' => 1547662996,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX8g3Kmx');
