<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4YP0Dh8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4YP0Dh8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4YP0Dh8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4YP0Dh8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4YP0Dh8\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '4YP0Dh8',
    'container.build_id' => '3b232cb3',
    'container.build_time' => 1547662430,
), __DIR__.\DIRECTORY_SEPARATOR.'Container4YP0Dh8');
